name: CI

on:
  push:
    branches: [ "main" ]


permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Build with dotnet
        run: dotnet build --configuration Release
      
      - name: Dotnet publish
        # working-directory: src/  
        # Sets a working directory, but messes up the folder structure. In this case, would change the cmd to:
        # dotnet publish GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj --configuration Release -o ../artifacts 
        run: dotnet publish src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj --configuration Release -o artifacts
            
      - uses: actions/upload-artifact@v4
        with:
          name: Zero_Hero_Project_Artifact
          path: artifacts/

  deploy_dev:
    name: Deploy App Dev
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Zero_Hero_Project_Artifact
          path: artifacts_donwloaded/


      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          

      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: app-zero-hero-github-actions-dev
          package: artifacts_donwloaded/



          

