name: CronJob Example

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: CronJob Example
    runs-on: ubuntu-latest

    steps:
      - name: Hello Modafoca
        run: echo "Hello Modafoca"
