name: CronJob Example

on:
  schedule:
    - cron: "* */1 * * *"  #-->At every minute past every hour.. Check some cron syntax later https://crontab.guru/#*_*/1_*_*_*

jobs:
  build:
    name: CronJob Example
    runs-on: ubuntu-latest

    steps:
      - name: Hello Modafoca
        run: echo "Hello Modafoca"