name: Secrets Workflow

on:
  pull_request:
    branches: [ "main" ]

env:
    env_variable: "Hello Modafoca"

jobs:
  build:
    name: Environment variable Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Echo environment variable
        run: echo ${{env.env_variable}}
        
      - name: Echo top secret variable
        run: echo ${{secrets.TOP_SECRET}}
    
    