name: Step - Deploy

on:
    workflow_call: 
        inputs:
            env:
                required: true
                type: string
        
jobs:
    
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Zero_Hero_Project_Artifact
          path: artifacts_donwloaded/


      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          

      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: app-zero-hero-github-actions-${{inputs.env}}
          package: artifacts_donwloaded/
 